### ISSUE TITLE
[Bug] OOM on first batch of when generating dashboards

### ISSUE THREAD

**Issue by hijohnnylin** [jbloomAus/SAEDashboard#3]
SAEDashboard saves cached activations to disk the first time that we generate dashboards. This allows us to just load from disk in subsequent generations of the dashboards.

The issue:
AFTER it has successfully saved the cached activations, there's an OOM when it first tries to use these cached activations. This does not happen on the second and later batches - on those batches where we are just loading the cached activations from disk, there is no OOM and the files are generated correctly.

Workaround:
Rerun the first batch, which causes it to load from disk and not have the OOM.

Potential Cause:
Something about caching the activations to disk the first time is using up memory that isn't being freed.

Log:
```
/home/ubuntu/saed/.venv/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████| 2/2 [04:00<00:00, 120.15s/it]
WARNING:root:You are not using LayerNorm, so the writing weights can't be centered! Skipping
Loaded pretrained model mistral-7b into HookedTransformer
Resolving data files: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 315.37it/s]
Skipping sparsity because sparsity_threshold was set to 1
Tokens don't exist, making them.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4096/4096 [00:27<00:00, 147.72it/s]
  0%|                                                                                                                         | 0/512 [00:00<?, ?it/s]========== Running Batch #1 ==========
  0%|                                                                                                                         | 0/512 [24:41<?, ?it/s]
Traceback (most recent call last):is: 100%|█████████████████████████████████████████████████████████████████████████| 384/384 [24:41<00:00,  3.82s/it]
  File "/home/ubuntu/saed/sae_dashboard/neuronpedia/make_batch.py", line 40, in <module>                                      | 0/128 [00:00<?, ?it/s]
    runner.run()
  File "/home/ubuntu/saed/sae_dashboard/neuronpedia/neuronpedia_runner.py", line 361, in run
    feature_data = SaeVisRunner(feature_vis_config_gpt).run(
  File "/home/ubuntu/saed/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/saed/sae_dashboard/sae_vis_runner.py", line 112, in run
    feature_stats = FeatureStatistics.create(
  File "/home/ubuntu/saed/sae_dashboard/utils_fns.py", line 526, in create
    quantile_data = torch.quantile(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.50 GiB. GPU 
Extracting vis data from cached data:   0%|                                                                                   | 0/128 [24:42<?, ?it/s]
Forward passes to cache data for vis: 100%|█████████████████████████████████████████████████████████████████████████| 384/384 [24:42<00:00,  3.86s/it]


╭─────────────────────────────────────────────────────────── Running Command for Batch #2 ───────────────────────────────────────────────────────────╮
│                                                                                                                                                    │
│ python make_batch.py res-je /home/ubuntu/Mistral-7B-Residual-Stream-SAEs/mistral_7b_layer_8                                                        │
│ /home/ubuntu/saed/sae_dashboard/neuronpedia/../../neuronpedia_outputs/mistral-7b_res-je_blocks.8.hook_resid_pre 1 4096 24576 128 128 2 2           │
│                                                                                                                                                    │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
/home/ubuntu/saed/.venv/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
WARNING:root:You are not using LayerNorm, so the writing weights can't be centered! Skipping
Loaded pretrained model mistral-7b into HookedTransformer
Resolving data files: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 321.29it/s]
Skipping sparsity because sparsity_threshold was set to 1
Tokens exist, loading them.
  0%|                                                                                                                         | 0/512 [00:00<?, ?it/s]========== Running Batch #2 ==========

```

**Comment by jbloomAus** [comment]
Should be fixed.
